name: Edgio Deploy Action
description: Greet someone and record the time
inputs:
  action:
    description: The action to take [deploy|update]
    default: deploy
  token:
    description: Edgio token when using the deploy action
outputs:
  buildUrl:
    description: URL of this build in Edgio developer console
  permalinkUrl:
    description: URL of this build permalink
  edgeUrl:
    description: URL of the live (edge) deployment
runs:
  using: node16
  main: dist/index.js
