name: Test Deploy Integrations
on: push
jobs:
  deploy-default:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration-tests/standard-deploy
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          path: ./action
      - name: Checkout test
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install modules
        run: npm ci
      - name: Deploy
        uses: ./action
        with:
          token: ${{secrets.deploy_token}}
          path: ./integration-tests/standard-deploy
