name: Test Deploy Integrations
on: push
jobs:
  deploy-default:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install modules
        run: |
          yarn install --frozen-lockfile
          cd ./integration-tests/standard-deploy
          yarn install --frozen-lockfile
      - name: Deploy
        id: deploy
        uses: ./
        with:
          token: ${{secrets.deploy_token}}
          path: ./integration-tests/standard-deploy
      - name: Verify deployment
        uses: actions/github-script@v6
        with:
          script: |
            process.exit(process.env.BUILD_URL.includes('default')?0:1)
        env:
          BUILD_URL: ${{ steps.deploy.outputs.buildUrl }}

  deploy-script:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install modules
        run: |
          yarn install --frozen-lockfile
          cd ./integration-tests/script-deploy
          yarn install --frozen-lockfile
      - name: Deploy
        id: deploy
        uses: ./
        with:
          token: ${{secrets.deploy_token}}
          path: ./integration-tests/script-deploy
      - name: Verify deployment
        uses: actions/github-script@v6
        with:
          script: |
            process.exit(process.env.BUILD_URL.includes('script-deploy')?0:1)
        env:
          BUILD_URL: ${{ steps.deploy.outputs.buildUrl }}

  deploy-custom:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install modules
        run: |
          yarn install --frozen-lockfile
          cd ./integration-tests/custom-deploy
          yarn install --frozen-lockfile
      - name: Deploy
        id: deploy
        uses: ./
        with:
          token: ${{secrets.deploy_token}}
          deployCommand: yarn custom:deploy
          path: ./integration-tests/custom-deploy
      - name: Verify deployment
        uses: actions/github-script@v6
        with:
          script: |
            process.exit(process.env.BUILD_URL.includes('custom-deploy')?0:1)
        env:
          BUILD_URL: ${{ steps.deploy.outputs.buildUrl }}
